# Generated by Django 4.2.3 on 2023-08-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_yourtask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourtask',
            name='status',
        ),
    ]
